version: '3.8'

services:
  backend:
    build:
      context: ./TodoApp
    ports:
      - "8000:8000"
    volumes:
      - ./TodoApp:/app
      - ./TodoApp/db.sqlite3:/app/db.sqlite3 
      - static-files:/app/static  
    environment:
      - DEBUG=True

  frontend:
    build:
      context: ./todofrontend
    ports:
      - "3000:80"

volumes:
  sqlite-data:
  static-files:  # Volume for static files
